language: ruby
before_install: gem update
rvm:
  - 2.1
  - 2.2
  - 2.1.10
  - ruby-head
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.10
    - rvm: jruby-head
    - rvm: ruby-head
